import 'package:get/get.dart';

class Languages extends Translations {
  @override
  Map<String, Map<String, String>> get keys => {
        'ar': arabicTrans,
        'en': englishTrans,
      };

  Map<String, String> get englishTrans {
    return {
      'greeting': 'Hello',
      'login': 'login',
      'register': 'register',
      'login_hint': 'please enter required info to login',
      'ForgetPassword': 'Forget Password?',
      'username': 'username',
      'password': 'password',
      'email': 'email',
      'haveAccount': 'already registered?',
      'settings': 'Settings',
      'lang': 'Language',
      'about': 'About',
      'account': 'Account',
      'ready?': 'Are you ready?',
      'next': 'Next',
      'Choose Your Language': 'Choose Your Language',
      'share': 'Sahre the App',
      "logOut": "Log Out",
      "Send Money": "Send Money",
      "Recive Money": "Recive Money",
      "Call Us": "Call Us",
      "Excange Prices": "Excange Prices",
      "Transfer Info": "Transfer Info",
      "USD to LYD:": "USD to LYD:",
      "EUR to LYD:": "EUR to LYD:",
      "Destination country *:": "Destination country *:",
      "Select Country": "Select Country",
      "Amount in LYD": "Amount in LYD",
      "Amount in Country": "Amount in Country",
      "Fee type *:": "Fee type *:",
      "Sender": "Sender",
      "Reciver": "Reciver",
      "Promotion Code:": "Promotion Code:",
      "Next Step": "Next Step",
      "choose recive type": "choose recive type",
      "Cash": "Cash",
      "Bank": "Bank",
      "Reciver Info": "Reciver Info",
      "name:": "name:",
      "Phone:": "Phone:",
      "Bank Name:": "Bank Name:",
      "Account Name:": "Account Name:",
      "Account Number:": "Account Number:",
      "Branche Name:": "Branche Name:",
      "home": "home",
      "my transfers": "my transfers",
      "profile": "profile",
      "Reference Number": "Reference Number",
      "Company Name": "Company Name",
      "Receiver name": "Receiver name",
      "Receiver phone": "Receiver phone",
      "Receive amount": "Receive amount",
      "Receive amount After Commision": "Receive amount After Commision",
      "Payment currency": "Payment currency",
      "Receive country": "Receive currency",
      "Send amount": "Send amount",
      "Commision Value": "Commision Value",
      "Fee Type": "Fee Type"
    };
  }

  Map<String, String> get arabicTrans {
    return {
      'greeting': 'أهلا بك',
      'login': 'تسجيل الدخول',
      'register': 'إنشاء حساب',
      'login_hint': 'الرجاء ادخال المعلومات المطلوبة لتسجيل الدخول',
      'ForgetPassword': 'نسيت كلمة المرور؟',
      'username': 'أسم المستخدم',
      'password': 'كلمة المرور',
      'email': 'البريد الألكتروني',
      'haveAccount': 'لديك حساب بالفعل؟',
      'settings': 'الإعدادات',
      'lang': 'اللغة',
      'about': 'نبذة عننا',
      'account': 'الحساب',
      'ready?': 'هل أنت مستعد ؟',
      'next': 'التالي',
      'Choose Your Language': 'أختر لغة التطبيق',
      'share': 'مشاركة التطبيق',
      "logOut": "تسجيل الخروج",
      "Send Money": "إرسال الأموال",
      "Recive Money": "استقبال الأموال",
      "Call Us": "اتصل بنا",
      "Excange Prices": "أسعار التصريف",
      "Transfer Info": "معلومات التحويل",
      "USD to LYD:": " الدولار مقابل الدينار الليبي :",
      "EUR to LYD:": "اليورو مقابل الدينار الليبي :",
      "Destination country *:": "الوجهة *:",
      "Select Country": "اختر البلد",
      "Amount in LYD": "المبلغ بالدينار الليبي",
      "Amount in Country": "المبلغ في الوجهة",
      "Fee type *:": "نوع العمولة *:",
      "Sender": "المرسل",
      "Reciver": "المستقبل",
      "Promotion Code:": "كود الخصم :",
      "Next Step": "التالي",
      "choose recive type": "اختر طريقة الاستلام",
      "Cash": "كاش",
      "Bank": "تحويل بنكي",
      "Reciver Info": "معلومات المستلم",
      "name:": "الأسم:",
      "Phone:": "رقم الهاتف:",
      "Bank Name:": "أسم البنك:",
      "Account Name:": "اسم الحساب",
      "Account Number:": "رقم الحساب :",
      "Branche Name:": "اسم الفرع :",
      "home": "الرئيسية",
      "my transfers": "تحويلاتي",
      "profile": "ملفي",
      "Reference Number": "رقم الحوالة",
      "Company Name": "اسم الشركة",
      "Receiver name": "اسم المستلم",
      "Receiver phone": "هاتف المستلم",
      "Receive amount": "المبلغ المستلم",
      "Receive amount After Commision": "المبلغ المستلم بعد العمولة",
      "Payment currency": "عملة الدفع",
      "Receive country": "عملة الاستلام",
      "Send amount": "المبلغ المرسل",
      "Commision Value": "قيمة العمولة",
      "Fee Type": "نوع العمولة"
    };
  }
}
